package com.healthconnect.user.model.enums;

public enum AppPageName {

    DOCTOR_PERSONAL_INFO,DOCTOR_EDUCATIONAL_INFO,DOCTOR_WORK_INFO,DOCTOR_DASHBOARD,HOSPITAL_BASIC_INFO,MOBILE_VERIFICATION_OTP,
    HOSPITAL_DASHBOARD,PATIENT_REG_INFO,PATIENT_DASHBOARD;
}
